scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/js/models/figure_model.js
static/figure/js/views/modal_views.js

Multiple pages

---

static/figure/css/figure.css
static/figure/js/models/panel_model.js
static/figure/js/views/panel_view.js
static/figure/js/views/right_panel_view.js
static/figure/templates/scalebar_form_template.html
static/figure/templates/scalebar_panel_template.html

Add an optional label to scalebar, E.g. 10 um.
Can also choose the font-size for the label.

Scalebar label

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/js/views/right_panel_view.js

Updating the PDF script to handle scalebar labels.

Handle scalebar labels in PDF script

---

static/figure/js/templates.js
static/figure/js/views/roi_modal_view.js
static/figure/templates/modal_dialogs/roi_modal_roi.html

Workflow improvement and small bug-fixes for cropping to ROIs.
For a range of time-points, choose shape on that time-point.

Crop to roi shapes

---

static/figure/js/views/figure_view.js
templates/figure/index.html

Handle "No Processor Available" as well as general errors from the script itself.
Shows error button which opens stderr in new tab.

Handle script errors

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/js/figure.js
static/figure/js/views/figure_view.js
templates/figure/index.html

Add option to export figure at TIFF (at 300 dpi).
Big refactor of Figure export script, using a new PDF export class and TIFF export subclass.

Export tiff

---

views.py

This adds RequestContext to render_to_response, making it compatible with changes in https://github.com/openmicroscopy/openmicroscopy/pull/3629.

render_to_response uses RequestContext

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/css/figure.css
static/figure/js/models/panel_model.js
static/figure/js/views/colorpicker.js
static/figure/js/views/figure_view.js
views.py

A few bug fixes and improvements to export script.

Bug fixes march 2015

---

scripts/omero/figure_scripts/Figure_To_Pdf.py

Add vertical labels in PIL by using a temp label canvas, adding text, rotating then pasting.
Seems to be pretty good now (screenshot of web on left and exported TIFF on right)

Handle vertical labels for TIFF figure export

---

static/figure/js/templates.js
static/figure/templates/scalebar_form_template.html

Missed the other case of symbol display in code (not exactly sure when this is used).

Follow-up fix of units display

---

_drafts/release-1.1.0.markdown
_includes/release_history.html
index.html

Update of the front page to add new features, install instructions etc.

Mentioning new features in index page

---

_includes/release_history.html
index.html

Index 1.1.0 (2)

---

README.md
templates/figure/index.html

To test:
- check the 3 links in README at https://github.com/will-moore/figure.
- In the figure app itself: 
- Goto Help > Home Page  and check you are sent directly to figure.openmicroscopy.org.
- Goto Help > About OMERO.figure and check the "figure Home page" link there is to figure.openmicroscopy.org.

Updating links to figure.openmicroscopy.org

---

_drafts/1.1.1-release
_includes/release_history.html
_layouts/default.html
_posts/2015-05-05-release-1.1.1.markdown
index.html

PR generated by FIGURE-help-release#6 (https://ci.openmicroscopy.org/job/FIGURE-help-release/6/). Merging this PR will update the live http://figure.openmicroscopy.org website.

Live deployment of figure.openmicroscopy.org

---

.travis.yml
scripts/omero/figure_scripts/Figure_To_Pdf.py
settings.py
urls.py
views.py

This PR simply reenables the Travis build and runs minimally flake8 for now. Additional validation tools (jshint or other) can be added in the future.
To test this PR, check Travis is green and the code diff is sensible.

Enable Travis in figure

---

package.json

Update package.json as suggested https://github.com/ome/figure/issues/112 by @joshmoore.

Update urls and version in package.json

---

_config.yml
_layouts/default.html

In preparation for 1.2.0 release, this updates the links to download the 1.2.0.zip.

Download links to latest

---

setup.py

Add classifiers section
cc @aleksandra-tarkowska @will-moore @sbesson @joshmoore 
see https://pypi.python.org/pypi?%3Aaction=list_classifiers

classifiers

---

README.rst

Fix hyperlink

---

licenses.txt

Update license
cc @will-moore 
The second part of the list was generated using https://www.npmjs.com/package/license-checker
``license-checker  --out original.txt`` 
Then by cleaning up the original output using 
https://gist.github.com/jburel/c20f821eb3d735599a0ec01f0b1f90cf

Update licenses list

---

CHANGELOG.md
README.rst

Prep changelog ahead of new release
cc @will-moore

3.1.0 history

---

omero_figure/utils.py

Bump version 3.1.0

---

CHANGELOG.md
omero_figure/utils.py

Update changelog for new release

Changelog 3.1.1

---

_posts/2017-07-03-release-3.1.1.markdown
_posts/2017-07-04-release-3.1.1.markdown
index.html

Add new entry for coming release

blog 3.1.1

---

CHANGELOG.md
omero_figure/utils.py

Entry for the coming 3.1.2 release
cc @hflynn @sbesson @will-moore

Release 3.1.2

---

_posts/2017-10-10-release-3.1.2.markdown
index.html

Bump version and add entry for coming release
cc @hflynn

blog 3.1.2

---

README.md

Noticed this while reviewing things for the docs training

Update doc link in README

---

.travis.yml
omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/views.py

Cherry-picked flake8 commits from #251

Flake8 fixes

---

omero_figure/utils.py

Bump version

---

README.rst

Add full url otherwise it does not work on pypi
cc @hflynn

Full url in README

---

CHANGELOG.md
omero_figure/utils.py

Changelog entry and version bump for the 3.2.1 release

Changelog & version bump 3.2.1

---

_posts/2018-02-12-release-3.2.1.markdown
index.html

See https://trello.com/c/YLxV2O0u/11-pre-release-announcement-website

Announcement for 3.2.1 release

---

README.rst
omero_figure/utils.py

Bump version ahead of coming release

Version 4.0.0

---

CHANGELOG.md

Changelog for 4.0.0.
Not included tiny bug fixes.

changelog for 4.0.0

---

_posts/2018-05-21-release-4.0.0.markdown
_posts/2018-05-22-release-4.0.0.markdown
index.html

Bump version and add announcement to figure.o.o
cc @will-moore

Announcement for 4.0.0

---

CHANGELOG.md
omero_figure/utils.py

Changelog for 4.0.1.
cc @jburel

Add changelog for 4.0.1

---

_posts/2018-08-28-release-4.0.1.markdown
index.html

4.0.1 announcement

---

CHANGELOG.md
omero_figure/utils.py

Changelog 4.0.2

---

_posts/2018-10-03-release-4.0.2.markdown

4.0.2 release announcement

---

.omeroci/app-deps
.travis.yml

This PR fixes recent issue with build and adds the option to release to pypi from travis
Check that travis remains green

Release travis

---

CHANGELOG.md

Add 4.1.0 entry to changelog

---

CHANGELOG.md
omero_figure/utils.py

figure 4.1.0

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/templates/figure/index.html
omero_figure/urls.py
omero_figure/views.py

See parent omero-web PR: https://github.com/ome/omero-web/pull/12

Django 1.9

---

.omeroci/app-srv
setup.py
test/integration/script.py

This is failing travis on a bunch of PRs (or has been patched to the PRs).
Would be nice to get this in ASAP.

flake8 fix

---

.omeroci/app-srv

Ported from https://github.com/ome/omero-figure/pull/351/commits/d5cddb0f4e6d3882edd9d70629ca406d86a0cb48
That commit was removed from #351 and wasn't needed to get travis passing, maybe due to other fixes elsewhere.
But perhaps we still want some of these changes?

app-srv changes from josh

---

README.rst

Add image.sc badge to README

---

CHANGELOG.md

Changelog 4.3.0

---

omero_figure/utils.py

Version 431

---

docs/figure_file_format.rst

Adding a figure file JSON spec to help users with creating files.
View at https://github.com/will-moore/figure/blob/figure_json_docs/docs/figure_file_format.rst

figure json docs

---

CHANGELOG.md

changelog 4.3.1

---

CHANGELOG.md

add entry for 4.3.2

---

.bumpversion.cfg
omero_figure/utils.py

Nothing to test
There was a manual step first to bring bump2version to the correct version then i used ``bump2version``

version change for release

---

CHANGELOG.md

PRs for next release (not all merged yet)

changlelog 4.4.0

---

.omeroci/app-deps

Update `grunt` and `nodejs` to fix build.
These commits were previously pushed to #430.

Nodejs update omeroci

---

omero_figure/views.py
test/integration/test_figure_files.py

Corresponds to https://github.com/ome/omero-web/pull/356

Django 3.2 update

---

.omeroci/app-srv

Cap reportlab 
similar to what we did in our ci-infra
Check that the build is green

cap reportlab

---

README.rst

See https://github.com/ome/omero-iviewer/pull/408/
cc @jburel

Install info clarify venv usage

---

README.rst

Clarify the virtual env to use

Clarify server dependencies installation

---

.github/workflows/publish_pypi.yml

Set the Python version to 3.9 in action

Set python version

---

omero_figure/templates/figure/index.html
src/js/views/labels_from_maps_modal.js

This should fix issue #501 
See PR #529 for last commit 73f6477 on underscore escape

Labels from ALL KVP 

---

src/js/models/panel_model.js

Should fix the time index offset no displayed mentionned here https://github.com/ome/omero-figure/pull/521#discussion_r1363509408

Enable time index offset

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

determine size using getbbox

---

CHANGELOG.md

changelog - see https://github.com/will-moore/figure/blob/changelog_6.1.0/CHANGELOG.md

Add changelog 6.1.0

---

.omeroci/app-deps

Bump nodejs and use dnf
This should fix the build failure reported by @will-moore

bump nodejs

---

CHANGELOG.md
README.rst

Changelog 7.0.0
See https://github.com/will-moore/figure/blob/changelog_7.0.0/CHANGELOG.md
cc @jburel

Add changelog 7.0.0

---

src/css/figure.css

Fixes #622.
Test edit labels form with browser on 90% zoom as described on the issue #622.

Fix wrapping of label X button. see issues/622
