ome/omero-figure

static/figure/js/models/figure_model.js
static/figure/js/views/figure_view.js
templates/figure/index.html

Fixes https://github.com/will-moore/figure/issues/34/
To test:
- Select different sized panels with different zoom levels and pixel sizes.
- Add similar sized scale bars to each, E.g. 5 microns.
- Select panels and choose toolbar 'Align Sizes' > 'Align Magnification'.
- All panels should be resized so that scale bars are same size in them all, using top-right panel as the reference.

Align magnification of selected panels

---

static/figure/js/models/figure_model.js
views.py

Need to be able to encode various unicode characters when we save files, and decode them when opening files.
Saved files need to use strings for file names (not unicode) so we also need to use the figure name encoded in the json for display etc, not the name of the file on disk.

Handle unicode characters by encoding/decoding

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/js/models/figure_model.js
static/figure/js/models/panel_model.js
static/figure/js/templates.js
static/figure/js/views/modal_views.js
static/figure/js/views/panel_view.js
static/figure/js/views/right_panel_view.js
static/figure/templates/scalebar_form_template.html
static/figure/templates/scalebar_panel_template.html
urls.py
views.py

Save units and symbols for pixel size X and Y. Use this simply for the Symbol shown in the Add Scalebar form and on scalebar label.
Also convert other units to MICROMETERS for the "Align Magnification" functionality.
Need to show correct symbols in PDF export on scalebar labels and in legend.

Basic unit support

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/css/figure.css

In order that we have a consistent panel background colour between Web and PDF when a panel is rotated or panned too much. Previously the background on PDF was black and light grey in Web.
Now it is white on both (which also allows rotating of a panel without the border showing up).

Panel background white

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/js/views/figure_view.js
templates/figure/index.html
views.py

Export option allows users to export the images used in a Figure alongside the PDF figure itself (as a zip).
For each panel this includes the Original rendered image and well as the cropped & rotated panel that was embedded in the PDF (both as tifffs). This gives greater clarity to the process of figure creation and also allows users to update the PDF with edited versions of the images within it.

Export images with pdf

---

scripts/omero/figure_scripts/Figure_To_Pdf.py

Simple fix to label and scalebar colors, particularly in Windows, E.g. with Sumatra-PDF viewer.
Also fixes more variable label colors (on Mac) available with the colorpicker.

Fix label colors in PDF export

---

views.py

This is https://github.com/will-moore/figure/pull/63 rebased onto master.
This adds RequestContext to render_to_response, making it compatible with changes in openmicroscopy/openmicroscopy#3629.

render_to_response uses RequestContext

---

static/figure/css/figure.css
static/figure/js/views/roi_modal_view.js
templates/figure/index.html

Addresses several points raised during OMERO.figure testing of the crop dialog:
To test:
- Crop dialog now has a short message instructing user to drag to select a region or pick ROI.
- If no ROIs on the image, show a message to indicate it.
- Dialog "OK" is disabled when the dialog is first shown and is only enabled when an ROI is picked or a region is selected.
- ROIs can be selected by clicking on the whole ROI row (don't need to click thumbnail) and this is indicated by mouse pointer and hover colour change.

Crop dialog fixes

---

static/figure/js/templates.js
static/figure/templates/scalebar_form_template.html

Fixes issue reported in pre-release testing.
Show unit symbol beside pixel size display (see screenshot):

Show pixel size with correct unit symbol

---

templates/figure/index.html

Feedback from Michael: most users won't know what markdown is: Make the info dialog more user-friendly.

Improve 'markdown info' dialog

---

static/figure/css/figure.css
static/figure/js/templates.js
static/figure/templates/viewport_template.html
templates/figure/index.html

Improve pixelated css styles to remove interpolation when zooming main figure and viewport.
Both now show pixelation at low dpi levels:

Fix pixelated css and add to viewport

---

static/figure/js/views/roi_modal_view.js

This PR ensures that the "OK" submit button on the crop dialog is not enabled when the region selected is zero or 1 pixel width or height.
To test:
- Open crop dialog, single click on image to add region that has zero width & height.
- OK button should be disabled.
- With a larger region, it is possible to drag the region outside of the area of the image.
- This should also disable the OK button.

Zero sized crop region

---

static/figure/js/templates.js
static/figure/templates/scalebar_form_template.html

Small fix to display of pixel size when it's not set.
Shows 'NOT SET' instead of 'null'.

Show 'Pixel Size NOT SET' instead of 'null'

---

static/figure/js/templates.js
static/figure/js/views/panel_view.js
static/figure/js/views/right_panel_view.js
static/figure/templates/viewport_template.html
templates/figure/index.html

Indicate which images have 'export_dpi' set by interpolating images as will be in the exported PDF.

If dpi is set, don't pixelate images

---

static/figure/js/views/modal_views.js

See https://github.com/will-moore/figure/issues/37
If a large image is added to a much smaller paper then we could end up with a negative scale number because the spacer around the image (image_width/20) was first subtracted from paper width before scaling. This is fixed by the first commit below.

Fix potential bug with adding big images to small paper

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
static/figure/css/figure.css
static/figure/js/app.js
static/figure/js/models/figure_model.js
static/figure/js/models/panel_model.js
static/figure/js/views/figure_view.js
static/figure/js/views/legend_view.js
static/figure/js/views/roi_modal_view.js
templates/figure/index.html

A bunch of follow-ups that came from OMERO.figure 1.1.0 release testing.
To test:
- When prompted to Save a newly created file when using browser back button, default name is same as elsewhere (not 'unsaved').
- Menu: File > Add Figure Legend  to add or edit a figure legend.
- Exporting 'with images' adds a README.txt file to the zip to explain what images are in the directories.
- Scalebars are 50% thicker, both in the web UI and exported figures.
- Legend formatting dialog link doesn't open new page etc.
- Clicking figure legend when collapsed expands it. Clicking when expanded starts edit.
- Clicking links within figure legend opens in new tab/window.
- Crop dialog should add the current panel region as initial crop selection (if zoomed in at-all).
- Export without saving works.

1 1 followup fixes

---

scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes problem with exporting figure without saving first.
To test:
- Create figure without saving
- Try to export PDF

Fix default figure name to be unicode

---

CNAME
_config.yml

This should allow to publish the figure GH pages under figure.openmicroscopy.org /cc @kennethgillen @will-moore @joshmoore @hflynn @gusferguson

Set up custom domain for production deployment of figure GH pages

---

_includes/github_ticker.html
_posts/2014-08-17-dev-jst-templates.markdown

Now that `master` and `develop` are in sync, we can switch to the default Git master branch as the development branch. If so, this PR modifies the GH pages resources to point at the commits on this branch instead of the develop one.
/cc @hflynn

GitHub pages preparation for switch to master branch

---

README.md
templates/figure/index.html

These 2 commits were already in "develop" but not in "master" since they got left behind around the time we switch main branch from "develop" to "master".
This was noticed by @jburel because the new Shapes PR: #100 is based off "develop" and contains these commits that should really be handled separately.

Readme url fixes

---

static/figure/js/models/figure_model.js

Noticed by @gusferguson and reported in https://github.com/ome/figure/pull/102#issuecomment-141024626
Since the size of A4 is 210 x 297 mm, (8.27 x 11.7 inches) at 72 dpi this is
595 x 842 points, so we need to start at this size so that we see no change when we
save 'paper setup', e.g. changing page count.
See https://en.wikipedia.org/wiki/Paper_size
To test:
- Create a new figure, add a panel and place at the bottom right of the page (to mark page size).
- Then edit "Paper setup", e.g. set page count to 2 and Save.
- Should see no change in size of page.

Fix the resize of paper

---

views.py

This fixes:
- imgData when image is not found. Previously it throws:
```
File "/home/hudson/OMERO.webapps/figure/views.py", line 125, in imgData_json
px = image.getPrimaryPixels().getPhysicalSizeX()
AttributeError: 'NoneType' object has no attribute 'getPrimaryPixels'
```
- add request to imageMarshal to make sure server settings are loaded

Fixing imgData

---

.dockerignore
Dockerfile
README.md

As requested in https://github.com/ome/figure/pull/107, opening as a new PR. This allows testing figure's demo task without the need for installing anything locally.

Add support for Docker

---

static/figure/css/figure.css
static/figure/js/templates.js
static/figure/templates/files/figure_file_item.html
views.py

This fixes the numerous 404 warnings caused by trying to use thumbnails from deleted images in the figure File > Open dialog.
E.g. nightshade:
```
Referrer: https://nightshade.openmicroscopy.org/figure/file/357017
Requested URL: /webgateway/render_thumbnail/3967151/
```
To test:
- Pick an image that you are happy to delete, add it into a new figure and save the figure.
- File > Open dialog should show the image thumbnail beside the new file in the list.
- Now delete the image (in webclient). 
- Return to /figure/ app and refresh the page, then File > Open again.
- Should see a grey thumbnail placeholder and if you check browser devtools you should see no 404 for render_thumbnail url.

Render thumbnail 404s

---

static/figure/js/views/modal_views.js

This fixes https://trello.com/c/eUiSnVRV/105-404-imgdata-nan
To test, add images to a figure, entering invalid ID(s)
E.g. As plain IDs:
```
2, blah, 3
```
Or in url form:
```
http://localhost:4080/webclient/?show=image-foo|image-8102|image-bar
```
Should see a popup with a suitable message.

Handle invalid IDs in addImages

---

static/figure/js/views/right_panel_view.js

Fixes a bug with setting line width using the controls at the top of Labels tab (which only showed as a bug when exporting the figure to PDF).
NB: I need to manually upload the export script to eel for this to be tested (export enabled).
To test:
- Create an ROI then use the line-width drop down at top of Labels tab to change line width.
- Try exporting as PDF.

Set line width as number, not string

---

package.json
scripts/omero/figure_scripts/Figure_To_Pdf.py
templates/figure/index.html

Fix bug in export when arrows are horizontal:
```
ShapeToPdfExport(self.figureCanvas, panel, page, crop, self.pageHeight)
File "./script", line 117, in __init__
self.drawArrow(shape)
File "./script", line 280, in drawArrow
lineAngle = atan(dx / dy)
ZeroDivisionError: float division by zero
```
To test, draw horizontal arrow and try exporting figure as PDF and TIFF.

Fix zero division error in export script drawArrow

---

_posts/2015-11-24-release-1.2.0.markdown

As discussed, make clearer that ROIs are not saved to OMERO.
cc @sbesson @jburel @joshmoore

Adding 'lightweight' and updating warning in 1.2.0 blog post

---

_posts/2015-11-24-release-1.2.0.markdown

typo fix 'Both' -> 'Some' in 1.2.0 blog post

---

index.html

As suggested by @jburel, not all users will restart web with ```$ bin/omero web stop``` and ```$ bin/omero web start```. Instead, simply instruct users to restart web according to their deployment setup.

Remove bin/omero web stop & start from figure docs

---

scripts/omero/figure_scripts/Figure_To_Pdf.py
urls.py
views.py

This should restore the Travis status to passing - see https://travis-ci.org/ome/figure/builds/101965790 for the current state. The alternative is to cap the version of flake8 installed in .travis.yml as we do on openmicroscopy.git. I have no strong preference either way.

Fix flake8 warnings for flake8 2.5.1

---

scripts/omero/figure_scripts/Figure_To_Pdf.py

This fixes the rotation of vertical labels when exporting as Tiff.
Noticed when testing Pillow 3.1.0 (not a problem on Pillow 2.9.0) See https://github.com/ome/omero-install/pull/86
To test, create a figure with vertical labels and export as Tiff using Pillow 3.1.0 (latest version).
Check vertical labels are in correct position.

Fix rotation of vertical labels with pillow 3.1.0

---

_includes/release_history.html
_layouts/default.html
_posts/2016-04-13-release-1.2.1.markdown
_posts/2016-04-20-release-1.2.1.markdown

Preparing release blog post for figure 1.2.1
Staged at http://figure.staging.openmicroscopy.org/
Check the "blog" and "releases" links and blog post text
NB: Date of release will be updated to the actual release date before merging.

Release 1.2.1 blog post

---

static/figure/figure.js
static/figure/js/views/figure_view.js

Simply disables the 'Save Figure' button right after the user clicks on it, to prevent multiple simultaneous save actions being triggered. See [Trello - Disable 'Save' when clicked](https://trello.com/c/mZsyPq8K/130-disable-save-when-clicked)

Disable save button

---

package.json
settings.py

We don't need to make this a configurable setting since it is
fixed for each release.
Also, the CUSTOM_SETTINGS_MAPPINGS is handled differently in OMERO 5.0
meaning that OMERO.figure breaks on 5.0
See https://trello.com/c/p31jKBy1/124-omero-5-1-x-and-5-0-x-compatible
To test:
- Check that the app still opens OK, and that ```Help > About``` shows OMERO.figure version 1.2.1-dev

OMERO_FIGURE_VERSION static variable

---

README.md
index.html

This removes install instructions for OMERO 4.4, which we don't test on now.
Clarifies that we support OMERO 5.0 and later. See: https://trello.com/c/p31jKBy1/124-omero-5-1-x-and-5-0-x-compatible

Remove OMERO 4.4 support from install instructions

---

static/figure/figure.js
static/figure/js/views/modal_views.js
static/figure/js/views/right_panel_view.js
templates/figure/index.html

See https://trello.com/c/yCvoAOs5/132-add-images-button-not-enabled-on-edit-paste
To test:
- With a new or existing figure, Add Images dialog. Use the right-click menu or browser top menu to Edit > Paste the image ID or URL.
- The 'Add Images' button should become enabled if the pasted text contains image ID (number).
- Add Images should then work as normal.

Add images button enabled

---

_config.yml

This updates the markdown support for building the figure website withe jekyll and gh-pages.
Hopefully staging should still look identical with this PR included although because the baseurl is different on the main branch, this change may need to be opened manually against the other branch.
I got some funny errors when I had it built locally, don't know if you have any ideas what these are about @will-moore?:
[2016-10-10 16:53:19] ERROR `/figure/css/pygment_trac.css' not found.
[2016-10-10 16:53:20] ERROR `/favicon.ico' not found.
[2016-10-10 16:53:20] ERROR `/apple-touch-icon-precomposed.png' not found.
[2016-10-10 16:53:20] ERROR `/apple-touch-icon.png' not found.
[2016-10-10 16:53:23] ERROR `/figure/css/pygment_trac.css' not found.
[2016-10-10 16:53:25] ERROR …

Fix jekyll errors building Figure website

---

_config.yml

Although I fixed the jekyll build as my local installation instructed, it seems gh-pages does not support pygments and we got an error for the website build when the live site was updated. This should fix it without altering the appearance of the site, as it's apparently what gh-pages is using now anyway.

Fix highlighter to gh-pages supported one

---

src/templates/channel_slider_template.html

This adds the missing ```channel_slider_template.html``` from #166.
Noticed by @bramalingam.
It wasn't picked up before because the compiled template was included in templates.js until recently.
To test:
- Check that channel sliders appear and are working normally, as described in #166.

Missing channel_slider_template.html from PR #166

---

src/js/views/right_panel_view.js

Fixes the deletion of labels that contain unescaped characters, e.g. single quotation marks ``` ' ```.
To test, create, labels with various escaped characters in ``` < > ' " ```.
Check you can update these labels (change text or color etc) and delete them.

Fix label delete

---

omero_figure/static/figure/css/figure.css
omero_figure/templates/figure/index.html
src/js/views/channel_slider_view.js
src/templates/channel_slider_template.html

Fix the display of Timestamp and LUT background for channel sliders.
Previously, timestamp label (for movies with timestamp info) was overlapped by the channel sliders and the channel sliders weren't showing LUT background correctly.
See before and after shots:
To test:
- Find an image with timestamp info. Check that label is not obscured.
- Test display of LUTs on channel sliders.

Slider bugfixes

---

omero_figure/views.py

This PR pretty-prints the json when saving a figure file, so that the
json in the file is human readable and more amenable to version control (since it's not all on one line).
See https://trello.com/c/sQw7eU4K/15-pretty-print-json-when-saving-to-file
To test:
- Save a figure file and note the file-annotation ID (in figure URL)
- Get the original file ID: ``` select file from annotation where id=32052```
- Check that the file is nicely formatted - Can download the file after manually attaching the figure file to an Image in the clients OR find the original file ID and go to /webclient/get_original_file/{id}/
- Refresh the figure page to check that the file still loads correctly.

pretty print figure json

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/static/figure/css/figure.css
omero_figure/templates/figure/index.html
src/js/views/panel_view.js
src/js/views/right_panel_view.js

Adds support for markdown in panel labels as requested in https://trello.com/c/BNjiEiAZ/3-labels-italics
To test:
- Create figure labels including *italics*, **bold** and ***bold italic*** styles with markdown.
- Check that they render correctly on the figure itself (in various locations on each panel).
- See that the [M] button beside the 'Add Labels' heading shows the Markdown info dialog.
- Check that the figure exports as PDF and TIFF with correctly formatted labels. 
- Also: fixed wrapping of figure labels when label is wider than panel (previously these wrapped in the figure app but not in exported PDF/TIFF). Now they extend up to 1 panel width either side of panel.
NB: Python markdown is not currently installed on eel server, so you will need to enter html labels to see these …

Markdown labels

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/static/figure/css/figure.css
omero_figure/templates/figure/index.html
src/js/views/figure_view.js

Allows export of a figure as new OMERO Images (one per page).
This is a preliminary part of https://trello.com/c/qqpED5kE/129-export-as-movie
To test:
- Choose "New OMERO Image" from the export options drop-down menu
- Export the figure... when done, should see a link to the new Image.
- Image will be named according to figure name and have the figure legend as it's description (if legend exists).
- Multi-page figures should create an Image per page, named ..._page_01 etc.
NB: I'll need to upload the figure export script before this is tested...

Export to omero

---

omero_figure/static/figure/3rdparty/shape-editor-2.0.0/shape-editor.js
src/js/views/channel_slider_view.js

As noticed by @bramalingam, if images have min-intensity above 9999 then the slider range ```min``` was incorrectly set at 9999, since this was hard coded.
Same is true for slider max.
This should now be fixed.
To test:
- For image where min pixel intensity of a channel > 9999, channel slider min should be set correctly.
- Same is true for images where max < -9999, but it might be tricky to find such an image, so I think we can assume that if the fix works for min, it also works for max.

slider range fix

---

src/js/app.js

As discussed with @bramalingam, this small change makes the ```figureModel``` into a global variable so that it is accessible to the browser devtools console.
See https://trello.com/c/5f4RniW4/159-omerofigure-plugins
This allows users to script various changes to the figure. 
E.g. pasting this code into the console will make a 'split-view' figure from all **selected** panels in the figure:
```
figureModel.panels.getSelected().forEach(p => {
var j = p.toJSON();
for (var c=0; c<j.channels.length; c++){
// offset to the right each time we create a new panel
j.x = j.x + (j.width * 1.05);
// turn all channels off except for the current index
j.channels.forEach((ch, i) => {
ch.active = i === c;
});
// create new panel from json
figureModel.panels.create(j);
};
});
```
Movie figure
``` …
```

figureModel_global_var

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
src/js/models/figure_model.js
src/js/models/panel_model.js
src/js/views/colorpicker.js
src/js/views/figure_view.js
src/js/views/modal_views.js
src/js/views/panel_view.js
src/templates/modal_dialogs/paper_setup_modal_template.html

Allows you to change the background colour of the pages.
See https://trello.com/c/55EzQq2e/14-set-page-colour
To test:
- Create a new figure with a few labels on the outside of the panel, at least 1 white, 1 black and 1 other color. White labels should be rendered Black (so you can see them against White page).
- Go to File -> Page setup and pick page colour.
- Page should update with chosen colour when Page_Setup dialog is "OK" & closed.
- Try setting the page colour to Black.
- Black labels should be rendered White (but not if moved to be within the panel instead of on the outside of the panel).
- Saving and refreshing/reloading figure should preserve page colour.
- Export of figure to PDF or TIFF should include coloured page.
NB: I'll need to upload script before the export is tested

Page colour

---

src/js/models/panel_model.js
src/js/views/roi_modal_view.js

Fixes a bug that has been around since LUTs were supported in OMERO.figure:
See https://trello.com/c/jOCVW3Co/8-bug-create-labels-from-channels-with-luts
To test:
- Set LUT on a channel
- Create labels from channels
- Labels from LUT channels should be grey
- Export should work as normal

Labels from channel with lut fix

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes bug with export of images that were added to figures before 'reverseIntensity' was supported (before 5.3.0).
Reported to @kennethgillen from nightshade:
https://trello.com/c/baovPrAJ/7-reverseintensity-keyerror-in-export
To test:
- I reproduced the bug by manually removing 'reverseIntensity' info from the JSON:
- File -> Export as JSON
- Copy this data, removing the ```, "reverseIntensity": true``` (only need to do this for a single active channel of a single image.
- Create a new figure with this text via File -> Import from JSON.
- Export of this figure should not cause any error.
cc @jburel - We should probably release this as a 3.1.1 bug-fix ASAP.

reverseIntensity keyError export

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes https://trello.com/c/YiuQbMBL/9-pagecolor-on-multi-page-pdf-export
To test:
- Create a multi-page figure and set the background colour
- Export as PDF
- Check that all pages have the page colour applied

Fix page_color on multi-page PDF figures

---

omero_figure/static/figure/css/figure.css
src/templates/image_display_options_template.html

While working on adding one more button, I noticed this very small change that would be useful as more buttons get added.

Use CSS rule for padding of image display options instead of hardcoded 2px

---

src/js/views/right_panel_view.js

While checking how the rotation is done to add a button for horizontal flip, I noticed this unused arguments and extra computations.

Remove unused function arguments and conversion between radians and degrees

---

omero_figure/views.py

This removes the local Figure method ```create_original_file_from_file_obj()``` and uses the Blitz Gateway
copy of the same method.
To test, check that saving a figure works OK.

remove_create_original_file_from_file_obj

---

src/templates/channel_slider_template.html

Simply changes the 'Reverse Intensity' label to 'Invert', to be consistent with the other clients.

Reverse intensity rename Figure

---

omero_figure/views.py

Fixes a minor bug where if a user has a middle-name set, they won't see any files listed when they first open the Files > Open dialog in figure.
Noticed for user-4 in web-dev-merge.
To test:
- Set a middle-name in user settings (or use user-4 in web-dev-merge) and in figure, Open Files dialog should show your own files when first opened.

list files user middlename

---

README.rst
SUPPORT.md

See https://trello.com/c/Gt8CIWJ0/598-support-files

Add SUPPORT.md & link from README

---

src/js/views/crop_modal_view.js

Fixes https://trello.com/c/imMLEy89/100-bug-figure-crop-dialog-thez-display
To test:
- Add rectangles on a multi-Z image in Insight, so that the Z range goes from below 100 to over 100 OR from below 10 to above 10.
- Add the image to a Figure and click on the Crop button to launch the dialog
- Check that the Z-index ranges are the same as created in Insight.
Before and after shots below:

fix theZ display in crop dialog

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
src/js/models/figure_model.js
src/js/models/panel_model.js
src/js/views/modal_views.js
src/templates/modal_dialogs/paper_setup_modal_template.html

This allows users to crop a figure to fit around panels.
See https://trello.com/c/lx5YoDTH/14-crop-page-to-panels
To test:
- With several panels on a figure...
- Choose File -> Paper setup and pick "Crop page around panels" from the Size options.
- When OK is clicked, the page should be cropped around the panels, with a small margin.
- This is added to the Undo queue and can be undone/redone in one action.
- Subsequent editing of page Size should show that we now have a "Custom" size, and can tweak custom size further.

Crop page to panels

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes https://trello.com/c/KEIu1LhB/17-bug-reportlab-34-export
This fixes an error seen when exporting a figure with lots of images, so that the Info section is more than 1 page. Only seen with reportlab 3.4.0.
To test:
- need to install reportlab 3.4.0
- Add lots (e.g. 20) images to a figure and export PDF
- Check that you can export 2 or more info pages
- NB: Also good to check that this doesn't break using reportlab installed via ```yum install python-reportlab``` as on web-dev-merge.

reportlab_3_4_bugfix

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

See https://trello.com/c/0TnhjDrs/1-export-bug-dx-none
This fixes a rarely seen bug (not sure how to reproduce it in normal use) in figure export.
Check that figure export still works as expected, with some images zoomed in and panned off-centre. Check cropped region is same in exported figure as in web.

export_bug_dx_None

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Parameters are not optional as indicated
This PR clearly sets the flag
Discovered while working on https://github.com/ome/omero-figure/pull/259
cc @will-moore 
This could be included in 3.2.0
we can then relax later on but at the moment it is broken

Scripts parameters

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
test/integration/test_figure_scripts.py

Fix an error when trying to export unsaved figures as PDF/TIFF
see https://trello.com/c/YkngbZ79/175-export-without-saving-figure
cc @will-moore 
To test:
* Open an image in Figure. **DO NOT SAVE THE FIGURE**
* Export the figure

Remove optional

---

omero_figure/templates/figure/index.html
src/templates/info_panel_template.html

A couple of minor fixes found in testing at https://docs.google.com/spreadsheets/d/1qdOAv0wUgAVHEtlVroOwkeNUoNwst-APSPFJk6-3Sz8
To test:
- Check that ```Help -> Home page``` and ```Help -> About``` then homepage link both go to https://www.openmicroscopy.org/omero/figure/
- Check that info tab can display big image sizes without overlapping the Edit button (size Z and size T now on separated rows)
/edit#gid=0

Layout and help url fixes

---

src/js/views/figure_view.js

From bug reported at https://docs.google.com/spreadsheets/d/1qdOAv0wUgAVHEtlVroOwkeNUoNwst-APSPFJk6-3Sz8/edit#gid=0
* Click New
* Add image ID 
* File -> Save. Use short-cut. 
* Do not Save. Click cancel
* Save button in the header is not longer active. 
* Cannot save from header any more
* Note that the button does not become active after actions e.g. rotate image
To test, repeat above but the Save button does not become disabled if we Cancel the save.
If save goes ahead, the Save button is disabled in the normal way.
The immediate disabling of the Save button when it's clicked was added to prevent Double-click performing a 2 Save POSTs when saving a pre-saved figure (no "Figure Name" prompt). Now we handle that elsewhere (not in the Save-As path).

save cancel fix

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
src/js/models/panel_model.js
src/templates/labels_form_inner_template.html

See https://trello.com/c/cVYdrcXM/131-no-time-stamp-use-t-index-instead
Adds support for labels showing T-index.
Useful if the image doesn't have timestamp metadata.
To test:
- Add Timelapse images to figure, with and without Time-stamp metadata.
- Choose to create label from ```Time (index)``` option (NB: this option will not be disabled in image with no timestamp metadata)
- Label should show the current T-index for the panel
- Export of the figure should also show correct T-index label for both images.

T-index label

---

omero_figure/templates/figure/index.html
src/js/models/panel_model.js
src/js/views/util.js

From comment on testing sheet
https://docs.google.com/spreadsheets/d/1qdOAv0wUgAVHEtlVroOwkeNUoNwst-APSPFJk6-3Sz8/edit#gid=0
"* File menu. When clicking on an item, a dialog pops up. To be consistent with Save a Copy...
All entries should have ... e.g. Open ..."
This PR adds the 3 dots to the commands which are incomplete (need other options chosen in a dialog). 
These are Open... and Import from JSON...
Also, improved layout of the drop-down menu options that have keyboard shortcuts, aligning the shortcut keys to the right of each menu.
To test:
- Check the File and Edit menus looks OK on Mac
- Check that on Windows the shortcut keys show ```Ctrl+N``` instead of apple key.

file_open_menu

---

src/js/views/svg_model_view.js

Fixes a small bug noticed on very large, high resolution monitors: https://trello.com/c/BnJ6wTz1/168-big-screens-svg-doesnt-resize-to-fit
To test:
- Open figure on a large, high resolution monitor
- Try drag-selection on the canvas (shows dotted selection outline) right down to the bottom-right corner. The drag outline should be able to extend fully down to the corner.

svg_resize_on_init

---

omero_figure/static/figure/css/figure.css
omero_figure/templates/figure/index.html
src/js/models/figure_model.js
src/js/views/figure_view.js
src/js/views/panel_view.js

Show a spinner while images are loading, from internal testing feedback at https://docs.google.com/spreadsheets/d/1qdOAv0wUgAVHEtlVroOwkeNUoNwst-APSPFJk6-3Sz8/edit#gid=0
Needs some thought about where and how big/obvious etc to show a spinner.
Currently this is quite subtle spinner in the Add Image button, similar to the figure export spinner.
This is not very obvious, but would probably be noticed by a user wondering whether anything is happening when loading takes a long time.

loading spinner

---

src/js/views/figure_view.js

As reported in testing sheet: https://docs.google.com/spreadsheets/d/1qdOAv0wUgAVHEtlVroOwkeNUoNwst-APSPFJk6-3Sz8/edit#gid=0
If a file is renamed and not saved, then File > Open (choose to save changes) doesn't show the new name in the list.
Also, if a New file is unsaved, then File > Open (choose to save new file) doesn't show the new file in the list.
Both these cases should be fixed and the new changes should be shown in the file list, since we now *wait* for the save call to return before we list files (previously, both calls were made asynchronously).
cc @pwalczysko

save before file open

---

src/js/views/right_panel_view.js

Since BlitzGateway methods for rendering big images don't yet support Z-projection, we disable the Z-projection button if any selected images are Big.
To test:
- Need a Big Image with Z-stack.
- Whenever any Big image is selected, Z-projection button should be disabled.
cc @jburel

Z-projection disabled big images

---

Gruntfile.js
omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/static/figure/css/figure.css
omero_figure/templates/figure/index.html
package.json
src/js/models/figure_model.js
src/js/views/right_panel_view.js
src/js/views/roi_modal_view.js
src/templates/rois_form_template.html
src/templates/shapes/shape_toolbar_template.html

The problem we find with big images is that the current strategy of scaling stroke-widths of ROI shapes to the image pixels means that when you zoom out, the lines get thinner and are invisible for Big Images, unless you set a stroke width of 100!
Also, the scaling of stroke-widths with images is inconsistent with OMERO.iviewer, so thin lines drawn on a Big Image in iviewer are invisible in figure.
This PR includes https://github.com/ome/shape-editor/pull/11 and means that when we zoom an image, the stroke widths stay the same. NB: since shape-editor is not released yet, I have copied the code over to test. When happy, can revert the TEMP commit and update version.
This means that all shapes on figure panels are shown on the figure at the same stroke-width, even when a panel is resized. …

Dont scale line widths on zoom

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Missed this from before.
To test:
- draw arrows of various strokeWidths
- export as PDF
- check that stroke-widths look correct compared with web view
Screenshot shows web (left), PDF before fix (centre) and PDF after fix (right)

Fix Arrow strokeWidth for PDF export

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

After parsing the JSON string, check if it's valid and fix it where we can.  Fixes issue #292

fix invalid panel dx/dy offsets

---

src/js/views/right_panel_view.js
src/js/views/util.js
src/templates/viewport_template.html

See https://trello.com/c/zXvu3QjV/202-bug-z-slider-bugs
To test:
- Clicking Z / T increment buttons should update Z/T labels and the slider position.
- Selecting the Z/T slider handle, then using the arrow keys to increment the slider should not nudge the selected panels in the figure.
- Check other Z/T slider & label functionality is unchanged: Test images with different Z/T sizes and values.

Z slider bugfixes

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Bug fix: See https://trello.com/c/S78nkV0c/203-bug-scalebars-in-exported-pdf-big-images (reported at https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=8523&p=19515)
To test:
- Check that scalebars are drawn correctly at various zoom levels of a big image.
- I did this by drawing ROI lines of known length in iviewer, using the scalebar on the image.
- Then add these Lines as ROIs in figure and add scalebars of corresponding length, e.g. screenshot below:
- Add some scalebars to non-big images to check they still work OK.
- Export to PDF & TIFF and check that scalebars show up at same level as in web.

big image scalebar fix

---

src/templates/modal_dialogs/roi_modal_shape.html

Don't show NaN for shape Z/T if undefined.
To test:
- Load ROIs with multiple shapes where Z / T are not defined.
- Shapes should not show Z / T as NaN (should be blank)
cc @jburel

Don't show NaN for shape Z/T if undefined

---

omero_figure/views.py

This fixes this issue https://github.com/python-pillow/Pillow/issues/2609 reported by @pwalczysko using ```pillow==4.2.1```.
To test, add a Big Image to figure and check that it renders OK.

fix render_scaled_region for Pillow 4.2

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

This PR includes additional functionality for the PDF/TIFF export:
- Shape fills (fully transparent when not given)
- Alpha channel for stroke and fill colors (defaulting to fully opaque when not given)
- Rotated rectangles (by processing rectangles as a polygon)
- Point shapes (as small circles processed as ellipses)
- Shape labels
None of these changes should impact the current export behavior for a given figure, though I need to do some more thorough testing.
Especially shape label rendering will need some more work, but opening the PR now for early review.

Additional export functionality

---

demo/static/json/load_web_figure/1.json

See https://github.com/ome/omero-figure/pull/326 - Ported fixes on that PR to the ```gh-pages-staging``` branch as required to release as described at https://docs.openmicroscopy.org/contributing/ci-docs.html#term-figure-help-staging
To test:
- See https://figure.staging.openmicroscopy.org/demo/#file/1
- Figure should display as normal (images loading etc) and can be edited (change rendering settings etc)

Fix JCB -> omero.lifesci.dundee.ac.uk links in demo 1.json

---

omero_figure/templates/figure/index.html
src/js/views/figure_view.js
src/js/views/labels_from_maps_modal.js
src/js/views/right_panel_view.js
src/templates/labels_form_inner_template.html

See https://trello.com/c/TT47EiZH/185-labels-from-map-annotations
And requested again at the BioImage Analysis Satellite Symposium
at Light Microscopy Australia 2019, Brisbane.
Demo at https://twitter.com/will_j_moore/status/1105389170065899522
To test:
- Select some image panels in Figure that have some Map Annotations (Key-Value pairs)
- In the "Add Labels" form, choose ```Key-Value Pairs``` in the drop-down menu
- Dialog should load all map annotations on the images and allow you to choose the Key. Numbers for each should indicate how many of the selected images have that Key (see screenshot)
- The Example Label at the bottom should give you an idea of what the label will look like ```Key: Value```.
- The ```Include Key in Label``` checkbox and choosing a new Key from the list should …

Create labels from map annotations

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

This improves the description of OMERO images created from figure export.
The image description now include references to the images that are contained in the figure (same as the PDF info page does for other forms of figure export).
This helps keep track of where an image-of-a-figure comes from.
To test:
- export a Figure to OMERO Image
- check the description for listing the images in the figure
- In Insight, the ```Image ID: 123``` should be rendered as a clickable link.

export to omero description

---

README.rst

The README didn't previously explain the need to update the script and several users have reported bugs due to not updating the script when they upgrade figure. Latest example is https://forum.image.sc/t/error-when-exporting-pdf-from-omero-figure-class-s-instances-can-only-be-saved-once-self-class-name/28915/4
This adds upgrade instructions to the README.

Add upgrade script info to README

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

This uses "Image:123" instead of "Image ID: 123" in the description of images created from figures.
As suggested (and supported) in https://github.com/ome/openmicroscopy/pull/6087#issuecomment-517166063
NB: That PR is not merged just now, so links aren't rendered, but layout looks cleaner:

Remove id from image link description

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

https://github.com/ome/omero-figure/pull/306 introduced a bug that causes transformations not to be applied to rectangles when exporting via PIL.  It probably went undiscovered since rectangles usually don't have a transformation (rotation) applied.

Apply transform to rectangles when exporting via PIL

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes adding Shapes to panels when exporting as TIFFs.
To test:
- Add a bunch of ROIs to some image panels
- Export as TIFF

script py3 fixes

---

README.rst

See https://forum.image.sc/t/omero-python-3-5-6-milestone-for-upgrade-testing/32120/5
and https://github.com/ome/omero-figure/pull/343/commits/de4baa608635793647f6962c6936eb92a6fe45bc
Previously we could install ```reportlab``` on CentOS with ```yum install python-reportlab``` but that doesn't target the virtualenv that we now use with py3.
See README "staged" at https://github.com/will-moore/figure/tree/pip_install_markdown_README

README says pip install reportlab and markdown

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

The unicode figure name issue was eventually addressed by changes to ci (see below).
The only remaining changes to this PR are a tiny bug fix.
To test unicode figure export:
- Create a figure named with unicode characters.
- Export as TIFF and/or PDF
- Add a second page (File -> Page setup) and add a panel to the new page.
- Export as TIFF (creates a zip containing a TIFF for each page).
File names should be unchanged.
Previous errors:
```
AttributeError: 'bytes' object has no attribute 'write'
```
<details><summary>show full error</summary>
```
Traceback (most recent call last):
File "./script", line 118, in compress
zip_file.write(fullpath, archive_name)
File "/opt/rh/rh-python36/root/lib64/python3.6/zipfile.py", line 1622, in write
with open(filename, "rb") as src, self.open(zinfo, …
```

Fix page count

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
src/js/models/figure_model.js
src/js/views/right_panel_view.js

See https://github.com/ome/omero-figure/issues/341
Fixes Figure export with Rectangles created from copy of crop region and paste to create Rectangle.
Previously shapes were created with "lineWidth" attribute instead of "strokeWidth".
This is fixed, and we also update previously created files when they are opened.
Workflow described in https://forum.image.sc/t/tips-tricks-gifs-from-uca-embrc-france-omero-database/32268
To test:
- Copy crop region from one panel
- Paste it as a new ROI on another panel (creates a Rectangle ROI)
- Export figure

Stroke width paste rect fix

---

omero_figure/templates/figure/index.html
omero_figure/urls.py
omero_figure/views.py
src/js/app.js
src/js/views/files.js

Fixes #361 
This allows Public user to see all files when in Figure File > Open instead of filtering to show only the files that you own (default behaviour).
This also adds a /figure/open/ URL so you can go directly to the File > Open dialog (in the same way that /figure/new/ takes you to the Add Images dialog.
To test:
- Enable public user
- Go to /figure/open/
- Should see the File > Open dialog already open, listing Files belonging to all users (not filtering for those belonging to public user).
- Clicking on a File should open it and update the URL accordingly
cc @manics

Public user open files

---

omero_figure/views.py

Fixes #336 
To test:
- Create a new figure (e.g. with a single image)
- Delete all panels so you have a blank page
- Save -> Choose a name -> OK
- Figure should get created. Can see it in File > Open etc.
- Can Open the file and add images later etc....

Fix Save Figure with no panels

---

src/js/views/channel_slider_view.js

If multiple images with same number of channels are selected, the channel buttons previously showed "undefined" if the labels didn't match.
Now we show no text.
Fixes #364.
Before:
After:

fix channel label mismatch

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/urls.py
omero_figure/utils.py
omero_figure/views.py
src/js/models/figure_model.js
src/js/models/panel_model.js
src/js/views/right_panel_view.js
src/templates/labels_form_inner_template.html

Fixes #375 
This adds supports for displaying timestamp labels in milliseconds or mins:secs.
Previously, all timestamps were loaded as *seconds* (timestamps were rounded when images were added to figures) and these integer values are stored in the figure JSON, so all existing figures can't have timestamps in milliseconds.
So, when older figures are open (VERSION 4) we now load un-rounded timestamps from the server to update those values in the figure JSON.
This allows us to choose "milliseconds" for timestamp labels (also "mins:secs") AND fixes the display of milliseconds for the label beside the T-slider.
To test:
- Use https://merge-ci.openmicroscopy.org/web/figure/file/25179 (user-3) which was created with VERSION 4 (last release). In this figure, timestamps are rounded to seconds …

Timestamp format millisecs

---

src/js/models/figure_model.js

Fixes #372.
To test:
- Save a figure with at least 2 panels, then refresh page - Save button will be disabled
- Select one panel and use arrow keys to nudge it. Save should be enabled.
- Repeat: select multi-panels and "Align-Left" or "Align-Top" - these should also enable the Save button.

Fix nudge save

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

This fixes a minor bug, brought to light by an error from user at #379.
The error was a KeyError because 'length' was missing from the scalebar dict (don't know why). The error came from the "Info-page" code, where we add scalebars to the the info page, and I noticed that this code was not taking the visibility of the scalebar into account.
Now, we ignore the hidden scalebars on the info page AND access length with ```scalebar.get('length') to avoid KeyError.
Fixes #379 
To test:
- Add scalebars of different lengths to 2 different panels
- Hide 1 of the scalebars and export the PDF
- The hidden scalebar should be ignored in the "Scalebar lenghts" of the page-info

Ignore hidden scalebars

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
src/js/models/panel_model.js
src/js/views/right_panel_view.js

Noticed bug with negative timestamps using hh:mm:ss format or mm:ss format since we round the hrs and minutes *down* in the UI and export script.
To test, check that the timestamps are shown correctly on this figure (screenshot shows current bug) e.g. ```0:00:-1``` and ```-1:59:59```

Fix negative timestamps format

---

README.rst

Fix README, remove old path/to/bin/omero

Remove path/to/bin/omero in README

---

CHANGELOG.md
omero_figure/omeroutils.py
omero_figure/utils.py
omero_figure/views.py

Re-organise code, having ``import omero`` prevents the deployment via travis
```
File "setup.py", line 31, in <module>
import [secure]ro_figure.utils as utils
File "/h[secure]/travis/build/[secure]/[secure]ro-figure/[secure]ro_figure/utils.py", line 21, in <module>
from [secure]ro.sys import ParametersI
ModuleNotFoundError: No module named '[secure]ro'
```
To test this PR:
* create a conda env with nodejs only (not omero)
* run ``python setup.py sdist``
Problem introduced in https://github.com/ome/omero-figure/pull/378
cc @will-moore

break utils.py

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

The escape function in the cgi module has been deprecated since
Python 3.2 [1] and has finally been removed in Python 3.8 [2],
resulting in the Figure_To_Pdf.py script failing to run under
Python 3.8.
This patch replaces the call to cgi.escape by html.escape, as
recommended by the Python developers.
[1] https://docs.python.org/3.7/library/cgi.html#cgi.escape
[2] https://docs.python.org/3.8/whatsnew/3.8.html#api-and-feature-removals

Replace cgi.escape by html.escape.

---

src/js/views/scalebar_form_view.js

The paper https://www.biorxiv.org/content/10.1101/2020.10.08.327718v1.full
mentioned in https://github.com/ome/omero-figure/issues/407
has this advice about scalebars:
Annotate scale bar dimensions on the image: Stating the dimensions along with the scale bar allows readers to interpret the image more quickly.
This PR encourages users to add the label on the scale bar by showing the label by default.
To test:
- Add a new Image panel
- Add a scalebar - the label should be shown by default.
- This won't change any existing figures where scale bars have been added to image panels already (even if the scale bar has subsequently been hidden) but if it's the first time that a scale bar has been added to a panel, the default 'show label' will apply.

scalebar show label by default

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes #406 
To test:
- Add scalebars with different units to different images
- Export as PDF
- Check that units are shown correctly in info page:

Fix scalebar units in PDF export

---

src/js/views/labels_from_maps_modal.js

Fixes #395
To test:
- Add duplicate Key-Value pairs to an Image
- Choose that Key when adding labels to the image from key-value pairs.
- Only 1 label should be created on each Panel for the duplicate Key-Value pairs.

Avoid duplicate labels from Key-Values

---

omero_figure/templates/figure/index.html
omero_figure/urls.py
omero_figure/views.py
src/js/app.js
src/js/models/figure_model.js
src/js/views/figure_view.js
src/js/views/util.js

Fixes #365 and fixes #352 
This handles errors when saving figures.
EDIT - we now store the current figure JSON in local storage and direct the user to login page which redirects to /figure/recover/ page which will load the recovered figure.
To test:
- Create or Edit a figure
- In another tab, log out of the webclient
- Save the Figure - the above dialog should be shown
- Clicking Reload button will open the webclient login page, then redirect you to `figure/recover/` page which should open the recovered file (unsaved). A dialog will ask if you want to clear the figure from local storage.
- When you save the recovered figure, it will create a new file, to make sure we don't overwrite another version of the saved file.
- File > Local Storage... gives you options to Clear local storage or …

Handle save errors

---

omero_figure/templates/figure/index.html
omero_figure/urls.py
omero_figure/views.py
src/js/models/figure_model.js
src/js/views/chgrp_modal_view.js
src/js/views/figure_view.js
src/js/views/files.js
src/templates/files/figure_file_item.html

Fixes #284 to show which groups each Figure is in and allow you to chgrp.
To test:
- File > Open list now includes groups and allows you to filter by Group just the same as Owner.
- File > Move Figure to Group... shows a chgrp dialog where you can pick a group to move to. Chgrp should be "instant" (we wait for a response instead of polling for completion) since it's not expected to take long. 
- This dialog also shows you which group the images in the figure belong to, with links to the images. This should help to ensure you keep the images and figure in same group.

Show group info

---

omero_figure/templates/figure/index.html
src/js/models/figure_model.js
src/js/models/panel_model.js
src/js/views/figure_view.js
src/js/views/util.js

This is a follow-up to #415. cc @jburel 
NB: this is on top of #416 (needed the new code from that PR), so that should be merged first.
To test:
- When a figure is recovered, the figure is cleared from local storage
- We use 'sessionStorage' for recovering figures. This is cleared when you quit the browser
- Figure is saved in a per-user storage.

Handle save errors2

---

omero_figure/templates/figure/index.html
omero_figure/urls.py
omero_figure/views.py
src/js/views/crop_modal_view.js
src/js/views/roi_loader_view.js
src/js/views/roi_modal_view.js
src/templates/modal_dialogs/roi_modal_roi.html
src/templates/shapes/shape_toolbar_template.html

Fixes #334 
Adds support for loading ROIs by page in the main `Edit ROIs` dialog, as well as the `Crop` dialog.
To test ROIs dialog...
- Find an image that has lots of ROIs - (over 500)
- Open the `Edit ROIs` dialog and load ROIs from OMERO
- The first page of 500 ROIs should load (as before) but if you scroll to the bottom, there is some info on how many you've loaded and a "Load More..." button.
- Clicking the button should load more. When there are no more to load, the button should be hidden. ROIs should be added when you click `Add` button for a ROI.
To test Crop dialog...
- Find an image that has lots of ROIs - (over 200) including Rectangles
- Open the Crop dialog. The first 200 ROIs are loaded and any Rectangles are shown as thumbnails for picking a crop region (as before).
- …

Rois pagination

---

src/js/models/panel_model.js
src/js/views/crop_modal_view.js
src/js/views/right_panel_view.js
src/js/views/util.js
src/templates/modal_dialogs/crop_modal_roi.html

Fixes #408 - copy rotated crop region and paste to ROI.
Also fixes #324
Rectangle ROIs don't support rotation, but this fixes the issue above by creating a Polygon to simulate a rotated Rectangle.
To test:
- Copy & Paste to duplicate a panel, then zoom in to crop, and rotate one of them.
- Copy the Crop region and Paste it as a new Shape on the un-zoomed panel - The new Shape (Polygon) should match the crop region:
- Copy the rotated Crop region, select the uncropped (unrotated) Panel and click Paste to paste the rotated crop region. The rotation should also be applied to the panel so that both images show the same rotated viewport.
- Crop the rotated panel using the "Crop" button. The 'initial' crop region should match the current viewport (see screenshot) and the updated crop region …

Crop rotation fixes

---

docs/demo/index.html
omero_figure/static/figure/css/figure.css
omero_figure/templates/figure/index.html
src/js/models/figure_model.js
src/js/views/figure_view.js

Fixes #368 
Also see https://forum.image.sc/t/spacing-between-images-in-omero-figure/68161
To test:
- select some images to align to grid
- In the drop-down beside the grid button, choose a grid gap size in pixels or choose 'custom' size
- If custom size is chosen, prompt asks for user input of size - only numbers are accepted
- Now, when the align-to-grid button is clicked, the panels will align with the chosen gap between them
- The default option "5% of panel width" is the current behaviour and can be chosen again if desired

Allow user to choose custom gap size for grid alignment

---

src/js/views/channel_slider_view.js

Fixes #467.
To test - see https://merge-ci.openmicroscopy.org/web/figure/file/95252 for example figure and images (user-3)
- Channel sliders should now have an increment of `0.01` allowing greater control, particularly with floating-point images with small ranges
- When you type values into the start/end input fields, they are no-longer forced to be Integers:

Use 0.01 increment for channel sliders

---

omero_figure/static/figure/css/figure.css
src/js/views/legend_view.js

This fixes a minor issue where the right-panel (or part of it like a drop-down list) falls behind the legend button (see screenshot). Only happens when the screen is small and/or the drop-down list is longer (see #472):
With the fix, the legend controls and the legend itself only shows above the right panel when you are editing the legend.

Only show legend-container above right panel when editing

---

docs/figure_file_format.rst
omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/static/figure/css/figure.css
omero_figure/templates/figure/index.html
omero_figure/urls.py
omero_figure/views.py
src/js/models/figure_model.js
src/js/models/panel_model.js
src/js/views/panel_view.js
src/js/views/right_panel_view.js
src/templates/labels_form_inner_template.html

PLEASE READ UNTIL THE END BEFORE MERGING (Figure_To_Pdf.py not tested and missing part about JSON version compatibility)
Dear OME team,
this pull request concerns labels, and in particular how special values like time, X/Y/Z or image name are handled.
Before, only "time labels" that were specified like [time-hrs:mins:secs] would be dynamically handled . But that worked only if the text of the label was exactly starting like "[time" and ending with an understood format like "-hrs:mins:secs]".
I changed the behavior so that a regex looks for a value between square brackets [], split the content separated by a "-" character, and replaces the text in the label according to what it found. With all the commits from this PR, the code recognizes:
* [time-...]
- index
- milliseconds
- ... (all …

Dynamic labels with regex

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Hi Will,
a quick fix for a bug I spotted in the pdf export. 
The "regular" text added after the 2nd dynamic label is cropped or ignored (`last_idx` was incremented instead of keeping track of the regex end position)
Should I make a post on image.sc to mention the bug and the steps to fix it? 
Replacing the latest script with this one should suffice.

Multi label text fix

---

docs/figure_file_format.rst
omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/static/figure/css/figure.css
src/js/models/figure_model.js
src/js/views/panel_view.js
src/js/views/scalebar_form_view.js
src/templates/scalebar_form_template.html
src/templates/scalebar_panel_template.html

Hey all,
This is a first draft to Fix #503 
I have added an additional input field to the scalebar_form panel and reordered the inputs to make space.
Adjusting the scalebar in the panel_view is done.
Known Issue: Site load show Empty string passed to getElementbyId(). This will also be returned multiple times when the scalebar is shown / hidden. Unclear where this is coming from
RFC: Is that approach in principle okay? If yes, I will try to track done that getElementbyId() thing and take a look on what needs to be modified in the export routines.
// Julian

Add option to adjust Scalebar width

---

src/js/models/figure_model.js

Hello Will,
tiny PR to replace `:` by `-` for the default figure filename, to solve https://github.com/ome/omero-figure/issues/314
That also includes the padding of date and time with zeros
If you would rather keep the `:`, I can revert to that format but keep the padding (otherwise reject the PR :D).
Side note, could you also close those solved issues:
- https://github.com/ome/omero-figure/issues/318  -> solved by https://github.com/ome/omero-figure/pull/472
- https://github.com/ome/omero-figure/issues/441 -> solved by https://github.com/ome/omero-figure/pull/481
- https://github.com/ome/omero-figure/issues/442 -> solved by https://github.com/ome/omero-figure/pull/481
Best,
Tom

Default figure filename to YYYY-MM-DD_hh-mm-ss

---

omero_figure/urls.py

See https://github.com/ome/omero-web/pull/458
These changes add support for Django 4.0 but are also compatible with current Django 3.2.x so can be released at any point.
To test:
- check that the figure app opens OK and you can load and save data. That should check enough urls to be sure it is working - don't need to check every url.

django 4.0

---

src/js/models/panel_model.js
src/js/views/modal_views.js

This PR should fix issues #511 and #512

Edit id z stack

---

docs/figure_file_format.rst
omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/static/figure/css/figure.css
src/js/models/panel_model.js
src/js/views/panel_view.js
src/js/views/right_panel_view.js
src/templates/labels/label_right_vertical_template.html
src/templates/labels_form_inner_template.html

Add the option to put labels to the right-vertical of the image

Right vertical

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes #522.
Use font.getbbox() instead of font.getsize().
Since font.getsize() is removed in Pillow 10 - as described at https://github.com/tensorflow/models/issues/11040

font getsize removal

---

src/templates/channel_slider_template.html
src/templates/labels_form_inner_template.html
src/templates/scalebar_form_template.html

Adding the choice for Cyan color in the display LUT.
Fixing #498 issue

add cyan color to drop down menu for LUT (fix #498)

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/templates/figure/index.html
src/js/models/panel_model.js
src/js/views/panel_view.js
src/templates/labels_form_inner_template.html

Adding the zoom level in the label list

Zoom label

---

src/js/models/panel_model.js
src/js/views/right_panel_view.js

Fix issue #502 by removing duplicate labels.
1. If a new label is added, the duplicated label is filtered before adding it to the figure
2. If an existing label is edited, the duplicated label is filtered after adding it to the figure.

Duplicated labels removal

---

omero_figure/templates/figure/index.html
src/js/models/panel_model.js
src/js/views/labels_from_maps_modal.js

Fix part of issue #486, related to 
I didn't change much because I think the markdown reading need to be preserved (see PR https://github.com/ome/omero-figure/pull/481#issuecomment-1288570316).
For each label added from a template (tags, channel name and key-values only ; image and dataset name are correctly handled), the underscore is escaped with a backslah ``replaceAll("_", "\\_")``. This enables a correct display of the label in omero.figure and it is compatible with ``Figure-to-pdf.py`` (``_`` and ``\_`` are identically interpretated in the script).
I've also integrated this feature in the PR #528.

Escape underscores on template labels

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Fixes the issue reported at https://github.com/ome/omero-figure/pull/521#pullrequestreview-1746222892
and described at https://github.com/ome/omero-figure/pull/521#issuecomment-1824264581
To test:
Try to export that same figure (or create another one where a panel is missing `pixel_size_z_symbol`, possibly by editing JSON etc).
cc @pwalczysko

Fix missing pixel_size_z_symbol in Figure_To_Pdf.py

---

omero_figure/views.py
src/js/models/figure_model.js

See https://forum.image.sc/t/misleading-error-message-in-omero-figure/68642
Also fixes #347.
This aims to improve the handling of errors when adding Images to Figures.
We try to avoid the errors reported on that issue, so that Images can load OK with missing pixel size info. 
Also, if there is any `Exception` message coming from https://github.com/ome/omero-web/blob/604d5279c96909a6862e4b1fc67de4f0a8699298/omeroweb/webgateway/marshal.py#L178 then we display it and don't try to add the Image to the figure.
To test:
One way to trigger one of the exception on #347 is to use the script below to unset pixelsize-Y. They should now be added to OMERO.figure OK (no error).
Invalid images (failed imports etc) should now give an appropriate error and NOT be added to the figure, but I don't know an …

Handle image loading errors

---

src/js/views/modal_views.js

Fixes #539 
To test:
- In page layout, choose "horizontal" page orientation
- Arrange some panels in a non-square layout (so you can tell the difference between width and height)
- Now in page layout again, choose "crop" to panels
- Cropped page should match the panels (not swap width/height as in bug on issue above)

Don't swap width/height when cropping page

---

src/js/views/modal_views.js

Hello @will-moore, 
I noticed that the feature ``Edit ID`` doesn't release the ``save`` button. 
Thus, it is not possible to save the figure and, if I close it without doing anything else, the ID edition is not taken into account.
I simply turn on the boolean of unsaved changes to release the button, so that we can click on it to save the figure.
Rémy.
Edit: doing ``ctrl``+``S`` with keybord worked well, even if the button was disabled

Enable save button when update ID

---

src/js/models/panel_model.js
src/js/views/labels_from_maps_modal.js

This PR is at a testing stage and relies on a changed function (`api_annotations`) from omero-web, inside a [parallel PR](https://github.com/ome/omero-web/pull/508).
Inherited annotations are decompressed, and the ann.link.parent is changed to the inheritor object. Like so, all further handling of the annotation is the same. No difference if the annotation was on the current image or on a parent object.
The implementation also checks that the query's result has the inherited annotations.

Annotation inheritance support

---

setup.py

Depends on https://github.com/ome/omero-test-infra/pull/68
These changes drop the custom `PyTest` test command and use the development test-infra branch to call `pytest` directly.

Integration tests: call pytest directly

---

src/js/models/panel_model.js

Fixes a bug introduced in #527: On `Edit ID` the panel zoom is updated to `undefined` since the incoming image data has no zoom info so `data.zoom` is always undefined.
This results in rendering errors - e.g. Zoom slider `0` and other `NaN` values below:
To test:
- Zoom a panel, then `Edit ID` to replace image with another.
- The zoom should remain unchanged and after de-selecting and re-selecting the panel (to trigger update of right panels) the zoom controls, viewport x, y, width, height etc should be rendered correctly.
cc @Rdornier

Don't update zoom to undefined on setId

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

Since we updated to use `x, y, x2, y2 = font.getbbox(text)` to get the height of text, the labels that are pasted on to the temporary canvas of that height are cropped at the bottom. We have removed the margin by using `height = x2 - x` but since the pasting at `x = 0` actually pastes *with* the margin (so the canvas is not big enough).
If we set the temporary canvas to grey for each label for debugging, we can see this effect more clearly:
In order to paste right at the top of the temp canvas (without the margin), we need to set the x coordinate to be negative margin:
This also positions the text the same as in the original figure:
Original figure:
NB: I also tested the export of *shape* labels (shown in 2nd screenshot above) which didn't need a fix to the `font.getbbox()` logic, but did …

Fix cropping of panel labels and float usage for shape labels

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

The logic selecting the best resolution for the export can select a plane as large as omero.client.download_as.max_size. With a default value of  144000000, this means regions as wide as 12k x 12k can be requested to the server.
This commit proposes to use the max plane width and height instead to select the appropriate resolution level. Both configurations default to 3k and are already used for identifying an image as "big" and navigating through the resolution levels.
This PR should be tested by running the figure export workflow on a large pyramidal images. Adjust the zoom so that the width & height is in the 3k-10k range and run the figure export script.
The server logs should include the arguments passed to the `rednderCompressed` API e.g.
```
2024-04-19 11:34:23,564 INFO  [ …
```

Figure_To_Pdf: use max plane size to select the appropriate zoom level

---

omero_figure/urls.py

I was reminded in prep for recent Web workshops that the Django recommended way of defining URLs is with `path()` function rather than `re_path()` and has been so since Django 3.2 at least.
E.g. see https://docs.djangoproject.com/en/4.2/topics/http/urls/
This updates OMERO.figure to use `path()` as a first step. Can think about omero-web and other apps too...
Expect no change in functionality.
To test all URLs...

Use path instead of re_path for all URLs

---

README.rst

Fixes #565 
Just a minor addition to the docs that omero.figure export can also be enabled by simply uploading the script through the web interface.
Best, Johannes

added info on figure scripts upload

---

README.rst

Fixes #571 
This capping has already been relaxed from the CI installation instructions in 065989a42b9cc9892684735f2346a4b085a7ad31. For Python 3.12 and above in particular, more recent versions of reportlab are required.

Remove the maximum reportlab version from the readme

---

vite.config.js

At least in my case, starting the app with `npm run start` did not refresh the page after modifications.
I found this fix for Vite 3.0.0 and higher (I have v3.2.10)
https://www.reddit.com/r/sveltejs/comments/vzdsc0/npm_run_dev_not_automatically_refreshing_with/

usePolling config for Vite auto refresh

---

package.json
src/css/figure.css
src/index.html
src/js/views/right_panel_view.js
src/templates/labels_form.template.html

Hello Will,
here's a PR to sort labels with a drag-and-drop. The cursor changes when hovering the labels, and moving the labels up or down, the order of the labels will be updated.
For the tests I conducted it works well. This handles:
* multiple panels (all labels equal, all different, mix of both)
* multiple label position (one set of positions is updated at a time)
This is the work from my new student Tehmina who is helping me with changes I'd like to make. @MinaEnayat

Label sorting with drag and drop

---

omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/urls.py
omero_figure/views.py
src/css/figure.css
src/index.html
src/js/models/figure_model.js
src/js/models/panel_model.js
src/js/views/info_panel_view.js
src/js/views/modal_views.js
src/js/views/panel_view.js
src/js/views/right_panel_view.js
src/js/views/scalebar_form_view.js
src/templates/image_display_options.template.html
src/templates/info_panel.template.html

Fixes #440.
This protects users from requesting Z-projections exceeding the `MAX_PROJECTION_BYTES` limit of `1024 * 1024 * 256` bytes or a value configured on the server `omero.pixeldata.max_projection_bytes`.
We always take into account the number of *active* channels rather than total channel count.
When a user enables Z-projection on an image, we test whether the full Z-range projection (with current channels enabled) exceeds the `MAX_PROJECTION_BYTES`. If so, the maximum number of Z-planes that can be projected is shown in red (tooltip includes the MAX_PROJECTION_BYTES limit). This limit will change when channels are turned on/off.
If a user exceeds the Z-projection limit using the Z-range sliders, we show a warning message instead of the Z-projected image. 
To test: (I have already …

Max projection bytes

---

src/css/figure.css
src/js/models/figure_model.js
src/js/models/panel_model.js
src/js/shapeEditorTest.js
src/js/shape_editor/rect.js
src/js/shape_editor/shape_manager.js
src/js/views/figure_view.js
src/js/views/right_panel_view.js
src/js/views/util.js
src/templates/rois_form.template.html

Fixes #319 
This replaces the tricky "create Inset" workflow (copy Rectangle and paste as Crop region or vice versa) with a single button click, and the Inset panel and Rectangle should stay in sync when either are updated.
To test:
- Select one or more panels and in the right-tab, under `ROIs`, click the "Create Inset" button
- This will create a new Inset Panel and a corresponding Rectangle:
- When you Pan, Zoom, rotate or Resize the Inset Panel, the Rectangle will update in sync (NB: we previously handled rotation when copying crop region and pasting as ROI by creating a Polygon instead of rotated Rectangle)
- When you edit the Rectangle (via the ROI dialog) the Inset Panel will update accordingly
- If you copy and paste the Inset panel to create e.g. split-view panels, each of these …

Inset feature

---

omero_figure/omeroutils.py

Changed `get_timestamps()` to revert back to the `timeIncrement` attribute of `Pixels` of an `Image`, if no `PlaneInfo` is found for it, or if the `PlaneInfo` did not contain `DeltaT` information.
If no `timeIncrement` attribute is found, it will just return 0 for all timepoints.
This does not account for any time offset that might have occured, i.e. the first image always is at 0s.

implemented get_timestamps() from timeIncrement attribute

---

setup.py

This removes the listing of `numpy` in test dependencies, which shouldn't be needed as `numpy` is already a dependency of `omero-py`. Seb noticed that we list `numpy` as a dependency as part of his work at https://github.com/ome/omero-py/pull/414.
It was added in https://github.com/ome/omero-figure/pull/356 due to `E       ModuleNotFoundError: No module named 'numpy'` but not sure why/where that was seen...

Remove numpy from tests_require in setup.py

---

omero_figure/urls.py
omero_figure/views.py
src/css/figure.css
src/js/views/channel_slider_view.js
src/js/views/lutpicker.js
src/templates/channel_slider.template.html
src/templates/lut_picker.template.html

Hey Will,
here's my implementation for the dynamic LUT with figure. 
I struggled with the png URL and png height, but it works now. 
I'm open for code refactoring suggestions.
It should also be compatible with omero-web<5.28.0, then using the lut png from omero-figure.

Dynamic lut for figure

---

omero_figure/omeroutils.py

Mirror fix of https://github.com/ome/omero-iviewer/pull/486
Please prioritize discussion in the omero-iviewer thread

Query timestamps from all planes when C or Z dimensions are not filled

---

src/index.html
src/js/views/files.js
src/templates/files/figure_file_item.template.html

See https://forum.image.sc/t/omero-figure-filtering-users-by-group/101933
When you filter the File > Open list by a Group, the owners list is also filtered to only show Owners within that Group.
Also, the columns now show the current status of Filtering:
This PR changes the display of the Owners menu in the File choose dialog. It does not change the actual behaviour of filtering Files.
To clarify the changes in this PR, I'll compare the behaviour BEFORE and AFTER...
NB: The Groups and Owners menus are only populated based on the Groups and Owners of the Figures you can access (that are loaded in the Files dialog). They are not generated based on Groups and Owners listed from OMERO. We also have no info on who is an Admin, so all users will get the same behaviour.
BEFORE:
- Initially the …

Filter owners and groups dropdown lists

---

omero_figure/omeroutils.py

Fixes #606 
Added a `None` check in [that line](https://github.com/ome/omero-figure/blob/master/omero_figure/omeroutils.py#L76)

fix NoneType exception on timeincrement

---

.bumpversion.cfg
omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
omero_figure/urls.py
omero_figure/views.py
package-lock.json
package.json
src/css/figure.css
src/html/dialogs/scriptManagerDialog.html
src/index.html
src/js/views/figure_view.js
vite.config.js

This addresses a couple of issues:
- Fixes #556 - Users get incorrect or failed figure export if using an old version of the script - Easily done if the script is not updated when OMERO.figure is upgraded. 
- Also makes it possible for Admins to use the OMERO.figure app itself to upload the current version of the script.
With this PR, the web app loads the `Figure_To_Pdf.py` script from within the Django app (using relative path from `views.py` -> `../scripts/omero/Figure_Scripts/Figure_To_Pdf.py` and uploads it to the server using the script service (if the current user is an Admin).
We also add a `FIGURE_VERSION` parameter to the `Figure_To_Pdf.py` script, with the default value being set to the release version of OMERO.figure. This allows the web app to use the script service to query …

Script version
